name: Build and Deploy with MicroK8s

on:
  push:
    branches: [main]

env:
  IMAGE_TAG: ${{ github.event.inputs.image_tag || 'latest' }}

jobs:
  build-and-publish:
    name: Build and Push Image to GHCR
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
    - name: Mostrar rama actual
      run: "echo 'Rama actual: ${{ github.ref }}'"

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set lowercase owner
      run: echo "OWNER_LC=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV

    - name: Build Docker image
      run: docker build -f Dockerfile -t ghcr.io/${OWNER_LC}/mcp:latest .

    - name: Push Docker image
      run: docker push ghcr.io/${OWNER_LC}/mcp:latest

    - name: Print pushed image URL
      run: "echo 'Imagen publicada: ghcr.io/${OWNER_LC}/mcp:latest'"

  deploy-onpremise:
    name: Deploy on MicroK8s On-Premise
    runs-on: main
    needs: build-and-publish

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Apply Kubernetes deployment
      run: sudo microk8s kubectl apply -f k8s/mcp.yaml
    - name: Restart Kubernetes deployment
      run: sudo microk8s kubectl rollout restart deployment/mcp-deployment -n mcp